### ISSUE TITLE
Doing any processing on Google Cloud Run causes "An error occurred while running the command", despite returning a 200

### ISSUE THREAD

**Issue by jdamour98** [Snazzah/slash-create#10]
Here's a simple example run function to replicate the issue. This is packaged in docker, and deployed on Google Cloud Run. Google Cloud Run does not support any async processing (because it bills by the time between receiving the request and sending response), so I need to do some processing before acking or sending any response.  

According to discord documentation, the interaction token is good for 15 minutes, and I can't find anything else about a timeout, so I don't think the issue is caused by discord.

```
  async run(ctx) {
    var subcommand = ctx.subcommands[0];

    if (subcommand == "sleep") {
      var delayMS = 10;
      console.log("functions working, sleeping " + delayMS + " milliseconds before responding");
      await sleep(delayMS);
      return "functions working";
    }

    if (subcommand == "noop") {
      console.log("functions working, noop");
      return "noop";
    }
  }
```

Running `/functions noop` returns a message and log line, as expected. 
```
functions working, noop
Info  POST 200  164ms  Discord-Interactions 1.0 (+https://discord.com)
```

Running `/functions sleep` causes discord to immediately respond in the UI with an error, 
```
An error occurred while running the command. Only you can see this • Dismiss message
```
however the logs also look fine:
```
functions working, sleeping 0 milliseconds before responding
Info  POST 200  31ms  Discord-Interactions 1.0 (+https://discord.com)
```

**Comment by jdamour98** [comment]
Ok, i read some more and learned sleep doesn't behave the same in nodejs as languages I'm used to. I've updated my example now to replicate my real issue:
```
  async run(ctx) {
    var subcommand = ctx.subcommands[0];

    if (subcommand == "sleep") {
      const snooze = ms => new Promise(resolve => setTimeout(resolve, ms));

      var delayMS = 1000;
      for (var option in ctx.options[subcommand]) {
        if (option == "delay") delayMS = ctx.options[subcommand][option];
      }

      var response = "functions working, sleeping " + delayMS + " milliseconds before responding"
      console.log(response);

      await snooze(delayMS);
      return response;
    }

    if (subcommand == "noop") {
      console.log("functions working, noop");
      return "noop";
    }

  }
```

and discord also updated their docs with my issue: 

> Interaction tokens are valid for 15 minutes and can be used to send followup messages but you must send an initial response within 3 seconds of receiving the event. If the 3 second deadline is exceeded, the token will be invalidated.

**Comment by Snazzah** [comment]
> > Interaction tokens are valid for 15 minutes and can be used to send followup messages but you must send an initial response within 3 seconds of receiving the event. If the 3 second deadline is exceeded, the token will be invalidated.

This is handled on master, but is yet to be released. Sorry for the inconvenience.

**Comment by jdamour98** [comment]
No worries, I didn't consider it a bug in the library at all. What it really means for me though is Google Cloud Run is ruled out as a hosting option unfortunately. Run only allocates CPU between the request being received and a response being sent. That means once an ACK is sent at 3 second mark, Run shuts down the container, so no async follow-up messages can be sent. 

I ended up deploying on Functions, which is by far the best platform for slash interactions (but just means no access to system packages). My repo is here if you're interested, feel free to link it as an example: https://github.com/jdamour98/discord-gcloud-commands
