### ISSUE TITLE
feat: Add channel types to options

### ISSUE THREAD

**Issue by Snazzah** [Snazzah/slash-create#142]
From https://github.com/discord/discord-api-docs/pull/3825:

| channel_types? | array of [channel types](https://discord.com/developers/docs/resources/channel#channel-object-channel-types) | if the option is a channel type, the channels shown will be restricted to these types |
|-|-|-|

**Comment by sudojunior** [comment]
**Unreachable types in this library...**

- ~~`GUILD_VOICE` = 2~~ as an Interaction event, not as a target.
- `GROUP_DM` = 3
