### ISSUE TITLE
How to do a poll?

### ISSUE THREAD

**Issue by EsteFilipe** [Snazzah/slash-create#144]
I'm trying to create a poll using a slash command. 

So basically I just want to do a message with an embed and once people react to that, I want to call a Lambda function which count the vote.

This poll will also have an end date at which another Lambda function will be called to perform an action with the poll results.

I'm using Lambda as the server, with this repository: https://github.com/ytausch/serverless-discord-bot

My main question here is, what's the best way to listen to those events (reaction and poll expiration date) using `slash-create`? I'm kind of lost in the documentation.  

--

I'm thinking that perhaps the most direct way would be creating the poll message using a slash command and then schedule another lambda to be triggered at expiration date, to do the final reaction counting (so counting the votes just at the end), but I'm wondering if there's a smarter way to go about it.

**Comment by Snazzah** [comment]
`slash-create` (or interactions) don't use reactions or have an interaction type for events. If you want to count something for each time someone votes for a poll, I'd recommend using select menus or buttons. You could also fetch the original message to read the reactions after it's over if you want. _(although I probably have not exposed that to the Message class, so that could be a PR.)_

**Comment by EsteFilipe** [comment]
I was trying to do it this way:

```
  async run(ctx) {
    // Reply immediately. The scheduling takes more than the timeout
    const response = await ctx.send("The poll goes here", {
      ephemeral: true,
    });

    await scheduleResultsCounting(response);
  }
 ```
 
 But `response` resolves only to `true` (I'd need the message ID), is this where you mean you haven't exposed to the Message class?

**Comment by Snazzah** [comment]
`await ctx.fetch()` after sending. That should give you the message object.

**Comment by EsteFilipe** [comment]
Just tried, but for some reason that makes the command fail with "This interaction failed". I'm using Lambda.
