### ISSUE TITLE
Ability to sending a message to the dm

### ISSUE THREAD

**Issue by DavichoStar** [Snazzah/slash-create#15]
In discord.js you can send direct messages with
```js
message.author.send(content)
```
and I would like that in the same way with this library it could be sent with for example
```js
ctx.member.send(content)
```
because sending it from the client is not it can simply if the user is not cached.

**Comment by Snazzah** [comment]
You can't send messages to direct messages from slash commands w/o using a bot client. slash-create isn't a bot client.
