### ISSUE TITLE
Let the GuildID property be an array

### ISSUE THREAD

**Issue by DavichoStar** [Snazzah/slash-create#16]
By placing this property as a matrix, you could create commands for X number of servers and not have to create a file for each server command if it will be the same. This can be solved in a number of ways, but it would be very useful if it could be placed directly in the *GuildID* property.
For example:
```js
{
    name: "premium",
    description: "Special command for 5 servers",
    guildID: ["ID1", "ID2", "ID3", "ID4", "ID5"]
}
```
This would also be useful when testing global bot commands where you have two or more servers to test on.

**Comment by Snazzah** [comment]
Possible, would have to rework command finding a bit during interaction. Might do it later on.
