### ISSUE TITLE
Discord: slash-create + discordjs buttons cause Unkonw Interaction 404

### ISSUE THREAD

**Issue by d3st1nyh4x** [Snazzah/slash-create#163]
404 unknown interaction when using button interactions causing the entire run function to throw and fail.
 `
 .........
 response: { message: 'Unknown interaction', code: 10062 },
  code: 404`

It only fails once I call a function that is part of the interaction collected by the collector in the on-collect event (i.reply, and i.update). 

If I call the methods on the message itself, I'm able to update the message and continue receiving interactions. This is particularly annoying when I want to tell users these aren't their buttons via ephemeral messages or when I want to update the look of a button via the interaction.update.

notice despite the try-catch around the entire contents of run this issue still halts my bot and throws a large error on the shell running it 

```js
const { SlashCommand } = require('slash-create');
const { MessageActionRow, MessageButton } = require('discord.js');

module.exports = class extends SlashCommand {
    constructor(creator) {
        super(creator, {
            name: 'bruh',
            description: 'Bruh',
            guildIDs: process.env.DISCORD_GUILD_ID ? [ process.env.DISCORD_GUILD_ID ] : undefined
        });
    }

    async run (ctx) {
        try{
            await ctx.defer();
            const row = new MessageActionRow()
                .addComponents(
                    new MessageButton()
                        .setCustomId('primary')
                        .setLabel('Primary')
                        .setStyle('PRIMARY'),
                );
            const { client } = require('..');
            const channel = await client.channels.fetch(ctx.channelID);
            const message = await channel.send({ content: 'Bruh!', components: [row] });
            
            // doesn't work either...
            // const filter = i => i.isButton() && i.user.id === ctx.user.id
            // const collector = channel.createMessageComponentCollector({ filter, time: 15000 });
            
            const collector = message.createMessageComponentCollector({ componentType: 'BUTTON', time: 15000 });
    
            collector.on('collect', async i => {
                try{
                    if (i.user.id === ctx.user.id) {
                        // message.edit(`${i.user.id} clicked on the ${i.customId} button.`) // this works
                        await i.update(`${i.user.id} clicked on the ${i.customId} button.`);
                    } else {
                        await i.reply({ content: `These buttons aren't for you!`, ephemeral: true });
                    }
                }
                catch(err){
                    console.log(err)
                }
            });
            
            collector.on('end', collected => {
                console.log(`Collected ${collected.size} interactions.`);
            }); 
            await ctx.sendFollowUp('bwo');
        } catch(err) {
            console.log(err);
        }
    }
};
```

My bot is actually built on top of [androz music-discord-bot](https://github.com/Androz2091/discord-music-bot), which sets up the discordjs client as an export of the main/index script.

**Comment by d3st1nyh4x** [comment]
The behaviour from discordjs seems to behave as intended, as it does, in fact update the message or reply with the ephemeral message; it just completely crashes the bot.

Also, the message is always spat to the console even when I pipe the output to a file (e.g. yarn start > logs.txt) 

I've tried wrapping this whole process in a promise that doesn't resolve until the collector calls end, thinking maybe it's because the original interaction ended; however, the result was the same.

**Comment by Snazzah** [comment]
It seems like they way the error is described, that the error may be with discord.js rather than slash-create. slash-create doesn't handle the functions for stuff like the `i.reply` function in the collector event.

You would have to paste the logs you get from the bot that's making it crash. If it's crashing from inside the collect event, try putting a try/catch statement inside that function, or add `.catch` to functions that return promises (which I'm guessing would be the functions within `i`).

**Comment by d3st1nyh4x** [comment]
I didn't mean to close this :( ;

Discodrdjs is claiming not to support third-party libraries, but I'm pretty sure these are separate technologies right? as this library calls the discord rest API directly right? (not through discord.js)

I should probably read up more on these libraries rather than just the documentation of the things I want to use lol...
