### ISSUE TITLE
`'@discordjs/collection@0.2.4'` requires Nodejs v16 but Vercel only supports Nodejs v14

### ISSUE THREAD

**Issue by Stochastic-Adventure** [Snazzah/slash-create#176]
Hi,

I was deploying my Discord Bot via Vercel. I understand that Node.js v16 just became LTS a few days ago but Vercel has not provided support yet. Right now I was trying to add a few more commands to my bot and Vercel started to complain about Node.js version.

![image](https://user-images.githubusercontent.com/73219028/140642192-406489ab-d219-4ae4-9bf7-ded782c1f50d.png)

Are there any ways to bypass this? I was using `slash-create@4.1.1` for my previous successful deployments. I tried v4.0.0 but it didn't work either.

Thanks in advance!

**Comment by zaourzag** [comment]
Yes there is! Look in the discord! I was having the same issue.

**Comment by Stochastic-Adventure** [comment]
For people using Vercel that encountered the node.js version problem, use this setup in your Vercel build:

![image](https://user-images.githubusercontent.com/73219028/140782219-c761920a-0534-48b0-bf2c-f72f3c409760.png)

Hopefully Vercel can provide Nodejs v16 support soon as it is now the LTS.
