### ISSUE TITLE
Missing access

### ISSUE THREAD

**Issue by VedantSharma7** [Snazzah/slash-create#180]
Hey, I have everything correct in my code, I'm using es6 module but when i do "node ." it receives "Missing Access" as a response. Do you know why? I have tokens, application ids and all that and its all correct but still not working.

**Comment by Snazzah** [comment]
Did you invite the bot with the `application.commands` scope?

**Comment by VedantSharma7** [comment]
Yes i did, it was working until i imported my whole bot to es6 module. You can find the bot code which uses slash-create by [clicking here](https://github.com/VedantSharma7/archive), if you ever gonna look at my shitty code and find some errors which are leading to the Missing Access error then do let me know.

**Comment by VedantSharma7** [comment]
and... the error which I got:

```PS C:\Users\stanp\Desktop\RetardedBot> node .
debug: undefined 1636734876200 /applications/:id/commands 200: 434ms (493ms avg) | 1/1 left | Reset 1636734876200 (0ms left)
debug: undefined 1636734876243 /applications/:id/guilds/888471444009398400/commands 403: 485ms (491ms avg) | 1/1 left | Reset 1636734876243 (0ms left)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

DiscordRESTError [403]: Missing Access
    at RequestHandler.request (C:\Users\stanp\Desktop\RetardedBot\node_modules\slash-create\lib\util\requestHandler.js:62:15)
    at SlashCreatorAPI.getCommands (C:\Users\stanp\Desktop\RetardedBot\node_modules\slash-create\lib\api.js:16:45)
    at SlashCreator.syncCommandsIn (C:\Users\stanp\Desktop\RetardedBot\node_modules\slash-create\lib\creator.js:255:41)```

**Comment by VedantSharma7** [comment]
Issue is Solved. I just reverted back from es6 to the common js. And It's working as of now. Feel free to close.
