### ISSUE TITLE
Error when using forward slash commands

### ISSUE THREAD

**Issue by Botreddai** [Snazzah/slash-create#232]
Every time I try to use a slash command, the bot keeps saying -botname- is typing, and doesn't respond to the interaction, and leaves an error in the console, undefined: 1
![Screenshot_20220126-144139_Chrome](https://user-images.githubusercontent.com/79804219/151218175-fbb5997f-af95-4cdd-9d6e-5b6ed56a5478.jpg)

**Comment by Snazzah** [comment]
Considering that the [API is having a major outage](https://discordstatus.com/), I can assume that this isn't the fault of the library.
