### ISSUE TITLE
A problem I forgot to mention

### ISSUE THREAD

**Issue by Botreddai** [Snazzah/slash-create#233]
and I forgot to mention the error that it gives next to the undefined 1, in the following screenshot you can see the error 
Sorry for the problems 🥺 
![20220126_211230](https://user-images.githubusercontent.com/79804219/151268240-37483057-8f15-41f8-97d8-2a22427957bf.jpg)

**Comment by sudojunior** [comment]
Does event debug reveal any useful details?
```js
creator.on('debug', m => console.log('slash-create debug:', m))
creator.on('warn', m => console.log('slash-create warn:', m))
creator.on('error', m => console.log('slash-create error:', m))
```
_Sourced from [this message](https://github.com/Snazzah/slash-create-template) by Snazzah._

> **Line 259**, as referenced in the stack trace (of compiled code), appears to indicate you've hit a ratelimit.
https://github.com/Snazzah/slash-create/blob/1db0dee70dfacd37812485bebe4865f72714a822/src/util/requestHandler.ts#L321-L329

**Comment by Botreddai** [comment]
![Screenshot_20220126-214716_Chrome](https://user-images.githubusercontent.com/79804219/151271134-cfe5bcef-066b-4377-a759-e327c3b7f48a.jpg)

**Comment by Botreddai** [comment]
I already found the solution, thanks anyway
