### ISSUE TITLE
Allow generating of command JSON asynchronously

### ISSUE THREAD

**Issue by multimeric** [Snazzah/slash-create#239]
This is a bit of a niche request, but basically in my app I need to fetch the command options (choices) dynamically from the DB, which necessarily requires an asynchronous "hook" for me to query the DB before I have to return the options object. Of course this can't be in the constructor, and also I can't just monkey patch in the `options` field later, since it has been set to `readonly`. I also don't want to delay registering the command until I load this choice data, because that would make app startup quite slow when the commands are already registered. So I'm wondering if we could add a new async function to `SlashCommand`, along the lines of:
```
async function getCommandJson(): Promise<PartialApplicationCommand>;
```

If this function is defined, then `syncGlobalCommands` will `await command.getCommandJson()` instead of just trying to access `command.commandJSON`.

**Comment by multimeric** [comment]
I small workaround (hack) I discovered:

You can define the command class with a minimal subset of the full command. The command name has to be accurate, and the command description has to be present but doesn't have to be correct:
```typescript
        super(creator, {
            name: "real_command",
            description: "fake description",
        });
```

Then later you can call the API directly with your full command description, to update the command definition:

```typescript
    const creator = new SlashCreator(...);
    // Abuse the slash creator API and directly push a command
    await creator.api.updateCommands([{
        // Long command description goes here
    }]
```

**Comment by Snazzah** [comment]
Not really going to add this one. Doesn't really benefit much from the usual use-case the library and seems a bit unnecessary to code around.

**Comment by Snazzah** [comment]
Following this up, seems like a valid use-case cropped up with #270.

Starting in `v5.4.0`, you can set your command properties asynchronously before syncing. It's not exactly overwriting commandJSON and the types don't support overwriting the name and description (overwriting the name would break the lib, but the description is fine), but this should suit your needs. This is mainly for asynchronously fetching localization for commands.

```
const { SlashCommand, CommandOptionType } = require('slash-create');

module.exports = class HelloCommand extends SlashCommand {
  constructor(creator) {
    super(creator, {
      name: 'hello',
      nameLocalizations: {
        de: 'hallo'
      },

      description: 'Says hello to you.',
      descriptionLocalizations: {
        de: 'Sagt hallo zu dir.'
      },

      // It's important to note that since option localization is passed straight to Discord, the prop names are snake cased.
      options: [{
        type: CommandOptionType.STRING,

        name: 'food',
        name_localizations: {
          de: 'lebensmittel'
        },

        description: 'What food do you like?',
        description_localizations: {
          de: 'Welches Essen magst du?'
        }
      }]
    });

    this.filePath = __filename;
  }

  // If you use any package like i18next and need to asyncronously set localization, this function is ran right before syncing the command.
  async onLocaleUpdate() {
    // this.nameLocalizations['da'] = i18next.getFixedT('da')('command.hello.name');
    // this.ddescriptionLocalizationse['da'] = i18next.getFixedT('da')('command.hello.description');
  }

  async run(ctx) {
    // ctx.locale
    // ctx.guildLocale

    return ctx.options.food ? `You like ${ctx.options.food}? Nice!` : `Hello, ${ctx.user.username}!`;
  }
}
```

**Comment by multimeric** [comment]
Excellent, so I can use `onLocaleUpdate` for arbitrary command updates that aren't related to locale? And it will always run, even if the user has say no locale settings or something?

**Comment by Snazzah** [comment]
It runs every time right before it's going to sync.
