### ISSUE TITLE
Express server example

### ISSUE THREAD

**Issue by chronos-ohm** [Snazzah/slash-create#274]
Is there some boilerplate code on how to set this up with an Express server?

I see here documented the basic usage https://slash-create.js.org/#/docs/main/latest/examples/webserver, but is there a repo somewhere with a full example for this, just like there is for Vercel?

**Comment by Snazzah** [comment]
You can use https://github.com/Snazzah/slash-create-template (`npx slash-up init`) and just replace `fastify` with `express`.
