### ISSUE TITLE
feat: support select menu in modal

### ISSUE THREAD

**Issue by sudojunior** [Snazzah/slash-create#338]
There is no official documentation to suggest the support of select menus in modals yet (which would probably appear [here (discord.dev)](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-interaction-data-option-structure) when that happens).

This would involve the behavioural change needed in `ModalInteractionContext` to achieve this support - though indication as to what happens in the future may require this to change once again.

https://github.com/Snazzah/slash-create/blob/aa88f6c023d4615091093a1754673d7110dd8007/src/structures/interfaces/modalInteractionContext.ts#L43-L53

Line 49: when additional components are added, this should not be dependant on [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) - but still, it's better than not doing it at all.
```ts
// ... values: {}, component{} of components[]
values[component.custom_id] = component.value ?? component.values;
// ...
```

**Comment by Snazzah** [comment]
Is this feature available now?

**Comment by Aericio** [comment]
Yes. I'm able to use them.
![image](https://user-images.githubusercontent.com/16523741/179142251-9784bef3-e860-48e6-99df-6cc12649ddbf.png)
![image](https://user-images.githubusercontent.com/16523741/179142300-6212327f-3ce4-4a6a-a8b3-95a8bb69db62.png)
![image](https://user-images.githubusercontent.com/16523741/179142288-f9c17aba-9bfe-41ea-a124-3d1bc17c5c84.png)

**Comment by Snazzah** [comment]
It's cool that it's a feature now, but there isn't a label like for text inputs? You can put in a PR for it later, but don't wanna merge *just* yet just in case Discord makes changes to this.

**Comment by FilipeAleixo** [comment]
This workaround stopped working. Now errors our with

```
DiscordRESTError [400]: Invalid Form Body
  data.components.1.components.0: Value of field "type" must be one of (4,).
```

Which type should be set instead of `never`?

**Comment by Snazzah** [comment]
@FilipeAleixo That error means Discord removed the ability to use dropdowns in modals. Like I said in the previous comment:
> … but don't wanna merge *just* yet just in case Discord makes changes to this.

**Comment by Snazzah** [comment]
Will close this until Discord decides to bring this back, or even acknowledge this in the first place.
