### ISSUE TITLE
Get a client from the command

### ISSUE THREAD

**Issue by Lokilife** [Snazzah/slash-create#35]
### This is a question.
I started using the library relatively recently, and I have a question. How can I get the Discord client from the command without using _require_? For example, output the client's websocket ping in the ping command. I looked through all the documentation, but didn't find anything related to this.

**Comment by Snazzah** [comment]
`slash-create` doesn't have anything that allows clients to hook into contexts or commands, since this is also meant for webservers. Your best bet is to actually `require` the client.
