### ISSUE TITLE
"BotName is thinking..." Issue

### ISSUE THREAD

**Issue by Shelly7w7** [Snazzah/slash-create#38]
I am not sure how is this being caused, it randomly started happening, where whenever I type a command, above the response discord adds "BotName is thinking...". An example is shown below:

![image](https://user-images.githubusercontent.com/36070804/112504572-281c3b80-8d49-11eb-8328-8085ed24bd42.png)

Acknowledgement is also set to true.

**Comment by Snazzah** [comment]
This is due to a new UI change and is resolved by #30. Expect a major release soon.

**Comment by Shelly7w7** [comment]
This still seems to be occurring even after updating to 3.0.0 @Snazzah
