### ISSUE TITLE
Support Google Cloud Functions

### ISSUE THREAD

**Issue by Snazzah** [Snazzah/slash-create#4]
> https://github.com/discord/discord-interactions-js/blob/main/examples/gcloud_function.js
> https://github.com/typpo/dinobot-discord/blob/main/index.js

Not too sure how to incorporate this, but it could be done. Never really used GCloud so I can't really test if I ever get a server class for this.

- [`@google-cloud/functions-framework`](https://www.npmjs.com/package/@google-cloud/functions-framework)

- [x] Create server class
- [ ] Documentation and instructions

**Comment by jdamour98** [comment]
You're looking for help with GCP/ [Cloud Functions](https://cloud.google.com/functions)? I have plenty of experience with it.

**Comment by Snazzah** [comment]
> You're looking for help with GCP/ [Cloud Functions](https://cloud.google.com/functions)? I have plenty of experience with it.

If you could try and extend the `Server` class to best suit GCP, you could create a PR with it. Not sure if the `(req, res)` arguments in the functions are express for instance.

**Comment by jdamour98** [comment]
I'll give it a stab tomorrow or this weekend. I was planning to deploy my bot on GCE, but GCF would be even better.

**Comment by Snazzah** [comment]
@jdamour98 Could you try using db0c2f9ec0e93d689253a0a81a8685f4d9a227aa? It should be enough from what i've seen.
If it does work, could you make instructions for new users?
```js
const { GCFServer } = require('slash-create');

creator
  .withServer(new GCFServer(module.exports))
  .registerCommandsIn(path.join(__dirname, 'commands'));
```

**Comment by jdamour98** [comment]
Worked right away! You're a beast. If you're interested I'll post my source and GCF setup

**Comment by Snazzah** [comment]
> Worked right away! You're a beast. If you're interested I'll post my source and GCF setup

@jdamour98 If you think it can helps, PR your steps in `docs/examples/gcf.md`, so it might help others.
