### ISSUE TITLE
Slash-create will spam error if Sync is impossible and error is not caught properly

### ISSUE THREAD

**Issue by Kio-td** [Snazzah/slash-create#40]
Slash-create 3.0, Gateway- Eris

I have bad coding skills. I say this because I have a catch-all error system that'll output the error to a Discord Channel and console. error(), before going on its way. I'm sure many bots do this for the sole reason of keeping their bot online.

Pair this with a broken script. and Slash will (supposedly) try using the broken command, over and over, and will attempt to continuously sync the broken command, until it's been rate-limited.

**Comment by Snazzah** [comment]
You should catch the error and put the error stack in this issue so I can figure out what's making it error. However, slash-create does not sync upon using a command, so it may be a user error.

**Comment by Kio-td** [comment]
When I launched it again, it seems that it's require-all that's going the trick, trying to add any command that looks even a small amount like js.

```
SyntaxError: Unexpected identifier
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at <Redact>\node_modules\require-all\index.js:56:46
    at Array.forEach (<anonymous>)
    at requireAll <Redact>\node_modules\require-all\index.js:34:9)
C<Redact>\slash_modules\campaignSettings.js:33
                                  required: false,
                                  ^^^^^^^^
```

**Comment by Snazzah** [comment]
Looks like an error requiring the file, and not actually a library issue.

**Comment by Kio-td** [comment]
I suppose this is true, but even still, perhaps there should be modifications in how require-all handles the files, (if there is any.)

**Comment by Snazzah** [comment]
This isn't an issue with `require-all` either. You most likely forgot to put a comma in the slash command options object.
