### ISSUE TITLE
Changing private class methods to be protected instead

### ISSUE THREAD

**Issue by DreamplaySE** [Snazzah/slash-create#418]
Hey! Awesome project you got here. I'm working with Cloudflare workers and was cleaning up the shim-code that is provided with the template and noticed a lot of workarounds to get access to the private methods. Could you change them to be protected so I can typesafely use them?

I'd like to publish the shim, rewritten with better cleanliness and updated for 2023, as a standalone package.

Best wishes ^^

**Comment by Snazzah** [comment]
Alright, but what methods exactly were you thinking of switching to protected?

**Comment by Snazzah** [comment]
I think those are good to change at least to allow others to modify freely.

**Comment by DreamplaySE** [comment]
Alright, I'll send a PR with those, cheers.

**Comment by DreamplaySE** [comment]
https://github.com/Snazzah/slash-create/pull/419
