### ISSUE TITLE
Using native discord.js message system causes the "Thinking issue"

### ISSUE THREAD

**Issue by Shelly7w7** [Snazzah/slash-create#42]
I am not sure where to report or seek help for this issue, but after some more testing and research, the "Bot is thinking" being stuck on unlimited loop is being caused if you use discord.js message system instead of this library's. You may ask why I use it? I use it because its easier to generate/construct an embed. Using the mentioned code below causes the issue. 

Now it may not be your issue, but I am not just reporting the issue but as well seeking help to somehow go around this or something so i can stick to the same method I used for dozens of commands:

```
   let guild = await client.guilds.fetch(GuildID);
   let channel = await guild.channels.cache.get(ctx.channelID)
   channel.send("message")
```

**Comment by Snazzah** [comment]
This isn't an issue with the library. Sending a message with `discord.js` will not complete the interaction and will leave the deferred message hanging. You have to send a message with `slash-create`. You can see a workaround with `discord.js`'s MessageEmbed in the [FAQ](https://slash-create.js.org/#/docs/main/latest/general/faq).
