### ISSUE TITLE
Including CloudFlare adapter

### ISSUE THREAD

**Issue by lukasfri** [Snazzah/slash-create#420]
I don't know if that is outside of the scope of this package, but it would be nice to include CloudFlare as an adapter/server.

**Comment by Snazzah** [comment]
You probably already saw the cf-worker example using a shim, since some things need to change in order to have it work properly. The server structure right now can't use workers as they should be used, but if I figure out a good way of doing this then I'll try it out.

**Comment by Snazzah** [comment]
Included in v6.
