### ISSUE TITLE
Timeout errors: Is it possible to ack or respond to a request in run and then continue processing?

### ISSUE THREAD

**Issue by asontha** [Snazzah/slash-create#429]
Hey! Really excited by what you've built but trying to figure out a usage pattern. I have a backend service that takes a while to compute a response (long running job) and I'd like to respond in 3 sec to avoid the timeout but then continue responding on the channel once the long running job completes. How would I do that using the slash-command framework?

```
async run(ctx) {

  # Respond quickly to avoid timeout and acknowledge users request

  # Trigger long running job

  return # Reply with context from long running job
}
 ```

**Comment by Snazzah** [comment]
You can respond with `ctx.defer()` to send a response and then keep using ctx methods to send a reply later with `ctx.send`. Keep in mind sending modals don't work after deferring.
