### ISSUE TITLE
Class constructor SlashCommand cannot be invoked without 'new'

### ISSUE THREAD

**Issue by n3oney** [Snazzah/slash-create#49]
Hello! I'm trying to use this library with TypeScript.
I'm currently on version 3.0.1

Here's an example command I have:

`HelloCommand.ts`
```ts
import { SlashCommand } from 'slash-create';

export class HelloCommand extends SlashCommand {
    constructor(creator) {
        super(creator, {
            name: 'hello',
            description: 'Says hello to you.'
        });

        this.filePath = __filename;
    }

    async run(ctx) {
        return `Hello, ${ctx.user.username}!`;
    }
}
```

And here's how I'm trying to register the command:
```ts
import { HelloCommand } from './commands/HelloCommand';

creator.registerCommand(new HelloCommand(creator)).syncCommands();
```

Whenever I try to construct the HelloCommand, I get this error:
```
TypeError: Class constructor SlashCommand cannot be invoked without 'new'
    at new HelloCommand (src/commands/HelloCommand.ts:5:9)
    at Object.<anonymous> (src/index.ts:20:22)
[ERROR] 16:05:14 TypeError: Class constructor SlashCommand cannot be invoked without 'new'
```

There's no errors when I import them using `.registerCommandsIn(directory)`, but that does not work with ts-node, so I'm trying to avoid it.

**Comment by n3oney** [comment]
This happens both when I try to pass a command instance and the class itself.

Here's where (in the library) the error is thrown:
slash-create/lib/creator.js:58:23
```js
registerCommand(command) {
        if (typeof command === 'function')
            command = new command(this); // <<<< here
```

**Comment by Snazzah** [comment]
You aren't exporting the command to `default`:
```ts
export default class HelloCommand extends SlashCommand {
```

You should also read the [FAQ in the master branch](https://slash-create.js.org/#/docs/main/master/general/faq) for an alternative solution to `ts-node`.

**Comment by n3oney** [comment]
Updated to default export, still the same thing...
![image](https://user-images.githubusercontent.com/30625554/114355350-a6f9dc80-9b6f-11eb-807a-f51e2c6bd892.png)
![image](https://user-images.githubusercontent.com/30625554/114355364-ac572700-9b6f-11eb-9ddf-1549661dad75.png)
![image](https://user-images.githubusercontent.com/30625554/114355381-b0834480-9b6f-11eb-9eeb-c469b645e85c.png)

**Comment by n3oney** [comment]
Let me try the devscript thing though... I hope that's not slower than ts-node-dev

**Comment by n3oney** [comment]
Installed ts-devscript,
`"dev": "devScript"`
Tried to run it, it does the same thing. I changed it to `.registerCommandsIn(path.join(__dirname, './commands'));`
![image](https://user-images.githubusercontent.com/30625554/114356441-e2e17180-9b70-11eb-9924-fab184b6ee0e.png)

**Comment by Snazzah** [comment]
I don't think something that simple that you have given (referring to the `HelloCommand.ts` codeblock) would compile over 58 lines. What is the target of your `tsconfig.json`?

**Comment by n3oney** [comment]
My target was ES5. After changing it to ES6 or newer it works fine.

**Comment by Snazzah** [comment]
I'll add a warning probably later that only ES6 and up will work.
