### ISSUE TITLE
Command Docs Generator

### ISSUE THREAD

**Issue by MeerBiene** [Snazzah/slash-create#51]
Add a doc generator that generates (markdown) docs from the commands.

**Reasoning**

Now that we know arguments and their types we could use this information to generate documentation. There could also be a property for a longer description or longer descriptions, this is just a quick idea I wanted to share.

As I already mentioned, I opened this issue to discuss the idea, if its decided to be added, I'd be happy to submit a pull request.

**Comment by Snazzah** [comment]
This seems like something that should be created separately from the project. Not everyone who uses the library may want generated docs, but you could make a separate package making this.
