### ISSUE TITLE
Consider improving support for not-node environments

### ISSUE THREAD

**Issue by Dougley** [Snazzah/slash-create#539]
The support for runtimes that lack node's packages (like `fs`, `util`, and `https`) is a bit lacking. 

The main culprit to this is that your code makes use of node internals at the top level of some exports, meaning that said runtimes either refuse to start or eventually complain about missing dependencies. For example, [`creator.ts`](https://github.com/Snazzah/slash-create/blob/master/src/creator.ts) contains top-level imports for `node:path` and `node:https`. If you'd want to package slash-create for use with something like Cloudflare Workers, you'd need to patch it to remove all node imports.

It seems your use of node's internals are for DX features. A possible solution could be to make a seperate 'web' export that just has the essentials for running slash-create but uses purely vanilla JS. From a quick look, this shouldn't be a massive undertaking since most of the core functionality uses vanilla JS already.

(Potentially related to #420)

**Comment by Snazzah** [comment]
The only real kind of things that use node packages would be the requester (which needs to be redone anyways) and registering commands in a folder. (Also not sure if tweetnacl would also be a problem)

A web export is probably the best way to go, since I can just split off the creator into a base, and nothing else really uses node things.

**Comment by Dougley** [comment]
Tweetnacl also doesn't bundle well. But if you only use it for Discord's signature validation algorithm, consider using native [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) with the `Ed25519` cypher instead. This is more performant, and tweetnacl is a pretty heavy dependency.

Few things to note: 
- SubtleCrypto is available on node's global namespace when using runtime flags or by default on >=19.x, but it's also available under `import('node:crypto').webcrypto.subtle`
- The `Ed25519` cypher is only on node >18.3.x. The older name for this cypher is `NODE-ED25519` (The old name is also used for CF Workers 😐)

**Comment by Snazzah** [comment]
Hmm, okay. I might just have a verify function as a creator option. I'm okay with just not using tweetnacl but may have the option to use it for Node versions below v18.3 (probably just as an optional peer dependency). The minimum node version for slash-create is on v14 but I'm not sure if I want to change it to v18 yet.

I'm working on redoing requests for the next major release, so I'll make sure to keep node dependencies in mind and test for that
