### ISSUE TITLE
Unable to respond to component interactions

### ISSUE THREAD

**Issue by iLikeToCode** [Snazzah/slash-create#606]
I tried many different ways, for example creator.registerGlobalComponent, but returning from that doesn't respond to the interaction like it does with slash commands. How do you respond to interactions?

**Comment by iLikeToCode** [comment]
The docs show .respond as a function of ComponentContext but it doesn't work

**Comment by sudojunior** [comment]
Hi there.

You may have referred to `respond` as an argument of its constructor _rather than it's protected twin_, which is used by response methods internally. `defer`, `send` and `editParent` are a few of the context methods that will use this.

https://slash-create.js.org/#/docs/main/v6.0.2/class/MessageInteractionContext
https://github.com/Snazzah/slash-create/blob/d5ba4622fc670236f57078bf6edd9b8c53b06b6c/src/structures/interfaces/messageInteraction.ts#L16-L29

**Comment by iLikeToCode** [comment]
Ok, thanks
