### ISSUE TITLE
Add ButtonStyle DANGER

### ISSUE THREAD

**Issue by fbrettnich** [Snazzah/slash-create#609]
Can we add the name `DANGER` for ButtonStyle (and leave `DESTRUCTIVE` as legacy to have no breaking change)?
The red button is called `DANGER` everywhere and I always type `DANGER` because I forget that it's called something else here 😅

Docs: https://discord.com/developers/docs/interactions/message-components#button-object-button-styles
Comment from Discord Staff that the image is wrong: https://github.com/discord/discord-api-docs/pull/3076#issuecomment-855103650

**Comment by Snazzah** [comment]
Added in [v6.1.2](https://github.com/Snazzah/slash-create/releases/tag/v6.1.2).
