### ISSUE TITLE
Add more infos to rawREST event

### ISSUE THREAD

**Issue by fbrettnich** [Snazzah/slash-create#610]
Can we pass more information in the `rawREST` event?
The information are already available and are passed as debug message a few lines later.

I would like to have the following information in the event to be able to create better stats on a dashboard:
- `request.route`
- `res.status`

---

https://github.com/Snazzah/slash-create/blob/acfa883e96458222d355a2c2099b0d706a9e8f64/src/rest/sequentialBucket.ts#L157-L166

**Comment by Snazzah** [comment]
You could still get the status code from `response.status` (which should've been typed anyways), as for request route, I could just give you the internal request and you can have that and more from it.

**Comment by fbrettnich** [comment]
You're right, I completely overlooked the response object.. 😅 and the internal request would be nice to have

**Comment by Snazzah** [comment]
Added in [v6.1.2](https://github.com/Snazzah/slash-create/releases/tag/v6.1.2).
