### ISSUE TITLE
Deprecated Undici dependency

### ISSUE THREAD

**Issue by CrazyKidJack** [Snazzah/slash-create#611]
When cloning this or the template repos, Dependabot complains that Undici 5.28.2 has a security vulnerability.
![image](https://github.com/Snazzah/slash-create/assets/43480837/3ff20007-3cb0-4613-8d43-0da74e3d8a18)

There is a 5.28.4 version that fixes the vulenrability. They have also release a new major version 6.13.0.
I checked with them and they said:
![image](https://github.com/Snazzah/slash-create/assets/43480837/6cf39b10-61f7-46b9-89dd-ab60e4ccefb4)

So I would not expect upgrading to the latest version (or to v5.28.4) to cause any compatibility issues.

**Comment by Snazzah** [comment]
Updated undici to `v5.28.4`.
