### ISSUE TITLE
Syncing Commands

### ISSUE THREAD

**Issue by The-Toonz** [Snazzah/slash-create#619]
So, I know that Syncing Commands **Globally** can take **` 2 hours `** to update on Discord.
But if you syncing the commands for a **guild** is like instant. But it's been 20 minutes and nothing.

I don't get any error, and the commands runs completely. And I don't know how I would debug to find the problem.
```js
async run(ctx: CommandContext) {
    if (ctx.options.globally) {
        await this.creator.syncCommands();
        return `Synced commands **GLOBALLY**!`;
    }

    // Sync commands in a Dev server.
    await this.creator.syncCommandsIn(Carbon.devServerID);
    return `Synced commands in **\`${Carbon.devServerID}\`**! **(_The Dev Server_)**`;
}
```

If I'm doing something very stupid, roast me so my brain can learn :sob:
_Note: Cloudflare Worker_

**Comment by Snazzah** [comment]
1. You probably shouldn't sync commands with a command, this is usually something you'd do after deploying a new version and syncing with `slash-up sync`.
2. It's probably syncing correctly in it's own context but did not take into account the new commands.
