### ISSUE TITLE
Lambda Docs: Markdown rendering broken

### ISSUE THREAD

**Issue by ytausch** [Snazzah/slash-create#63]
### Screenshot
> ![Screenshot](https://user-images.githubusercontent.com/25906270/119827562-92905a00-bef9-11eb-939d-976c8744ce77.png)

Link: https://slash-create.js.org/#/docs/main/latest/examples/lambda

GitHub renders it properly: https://github.com/Snazzah/slash-create/blob/master/docs/examples/lambda.md

**Comment by Snazzah** [comment]
Fixed in 814843382c145ebcdcb6d7b3f926f351b9b4b28d
