### ISSUE TITLE
Requiring the client doesnt work as described

### ISSUE THREAD

**Issue by beefthief** [Snazzah/slash-create#70]
Passing the client instance as described in the [FAQ](https://slash-create.js.org/#/docs/main/latest/general/faq) and in #35 doesn't work; an error is returned when calling the command and a Node warning appears on the console.

Attached are screenshots of my exact setup (which, apart from using `dotenv` for the bot itself, is identical to the examples):
![main_file](https://user-images.githubusercontent.com/83414854/124074974-3649ba00-da12-11eb-9375-56e1e7f78e5a.png)
![command_file](https://user-images.githubusercontent.com/83414854/124075022-4366a900-da12-11eb-9c20-f787ec8a9a48.png)
![error_msg](https://user-images.githubusercontent.com/83414854/124075044-48c3f380-da12-11eb-926a-af786755314e.png)

Using `node --trace-warnings bot.js` as the error message specified allowed me to trace the issue to the command file itself, which was indicated by the `${client.user.id}` bit I appended at the end of the command, and subsequently ran without providing the `food` option.

I have also attempted to add `this.client = client` to the command constructor as well, but the results were the same.

**Comment by Exhabition** [comment]
As the error suggests, your requiring of the bot leads to a circular dependency, I would suggest doing some research online to figure out what that means and how that is caused.

> I have also attempted to add this.client = client to the command constructor as well, but the results were the same.

If you attempted this, keep in mind that this will still create a circular dependency error if the client is still the client you are trying to require. Instead pass the client along in the constructor and remove `require("..bot.js")` parts.

You would get something like
```js
constructor(client, creator) {
        // your super and whatever

        this.client = client;
}
```

I am afraid that if you want to solve it this way however, you need to rewrite your registering of commands part as you would need to pass the client to the constructor of the commands, something like `new YourCommand(client, creator)` and as far as I am aware `registerCommandsIn` doesn't support that (you may correct me on that if I am wrong)

**Comment by Snazzah** [comment]
I've updated the FAQ in c5bbfac2e4f7d5162c17c1d598445d133de8894e which should give a better alternative.

**Comment by Shironep** [comment]
the issue is because you put **module.exports = client;** below the **creator.withServer()**, i had the same, and i fixed by moving module.exports above the creator.withServer()

just saying, if someone still wants to use the module.exports alternative

**Comment by beefthief** [comment]
> the issue is because you put **module.exports = client;** below the **creator.withServer()**, i had the same problem, and i fixed by moving module.exports above the creator.withServer()
> 
> just saying, if someone still wants to use the module.exports alternative

This worked in the manner I was initially expecting when I opened this issue. Thanks for the alternative!
