### ISSUE TITLE
Another Question

### ISSUE THREAD

**Issue by Shelly7w7** [Snazzah/slash-create#9]
So it works after using the example, but unlike other libs, when you use a command the log doesnt pops up which says something like "User used /hello" thingy, is it a discord bug or do I have to enable something?

**Comment by TheCuteFoxxy** [comment]
```ctx.acknowledge({
   includeSource: true
   });```

**Comment by Snazzah** [comment]
@Shelly7w7 Following what @TheCuteFoxxy posted:

For acknowledgements: `ctx.acknowledge({ includeSource: true });`
For messages: `ctx.send('text', { includeSource: true })`
For uto-acknowledgements ***(on soon-to-be 1.3.0 release)***: Set `autoAcknowledgeSource: true` in creator options
