### ISSUE TITLE
Use Id instead of ID

### ISSUE THREAD

**Issue by Androz2091** [Snazzah/slash-create#98]
I am using slash-create in several project and would like to be able to use Id instead of ID for consistency, as discord.js does in v13. (https://github.com/discordjs/discord.js/pull/6036)
Thank you for your lib it's awesome

**Comment by sudojunior** [comment]
I hate to disturb the peace, but I will leave my thoughts on analysing the possible changes and discussions for the differences between the two packages.

- The proposed would result in a breaking change (regardless of how it progresses as a release) {}.
  - [`MessageInteractionContext`](https://slash-create.js.org/#/docs/main/latest/class/MessageInteractionContext) <- [`CommandContext`](https://slash-create.js.org/#/docs/main/latest/class/CommandContext), [`ComponentContext`](https://slash-create.js.org/#/docs/main/latest/class/ComponentContext)
    - [`#channelID`](https://slash-create.js.org/#/docs/main/latest/class/MessageInteractionContext?scrollTo=channelID)
    - [`#guildID`](https://slash-create.js.org/#/docs/main/latest/class/MessageInteractionContext?scrollTo=guildID)
    - [`#interactionID`](https://slash-create.js.org/#/docs/main/latest/class/MessageInteractionContext?scrollTo=interactionID)
    - [`#messageID`](https://slash-create.js.org/#/docs/main/latest/class/MessageInteractionContext?scrollTo=messageID)
    - [`{ComponentContext}#customID`](https://slash-create.js.org/#/docs/main/latest/class/ComponentContext?scrollTo=customID)
  - [`Message`](https://slash-create.js.org/#/docs/main/latest/class/Message)
    - [`#channelID`](https://slash-create.js.org/#/docs/main/latest/class/Message?scrollTo=channelID)
    - [`#webhookID`](https://slash-create.js.org/#/docs/main/latest/class/Message?scrollTo=webhookID)
  - [`SlashCommand`](https://slash-create.js.org/#/docs/main/latest/class/SlashCommand)
    - [`#guildID`](https://slash-create.js.org/#/docs/main/latest/class/SlashCommand?scrollTo=guildIDs)
    - [`SlashCreatorOptions.applicationID`](https://slash-create.js.org/#/docs/main/latest/typedef/SlashCreatorOptions)
- The changes stated in the attached issue is based on a task they've had on their backlog for '2 years' as Kyra has said.
- While this package would likely follow convention, the aforementioned is not *standard*. Furthermore, `discord.js` is not explicitly supported under convention (given that it doesn't support structures like `MessageEmbed`, therefore forcing a raw json payload to be used).

With all that said, I am only a past contributor - I do not know what he may think about this just yet, but I can provide the insights necessary to achieve an adequate conclusion.

**Comment by Snazzah** [comment]
I don't think this is important enough to merit breaking changes. I'm not trying to follow discord.js' standard with this library (this more falls in line with eris' naming convention anyways) nor conform with how they do stuff. As @sudojunior stated, `MessageEmbed` isn't directly supported.
